### ISSUE TITLE
Task: MVP UX/UI Test + Feedback! 🙏 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#140]
Hi @Stephanymtr as you noted privately, you need a better way of managing your **Todo List**. We _agree_! 😖 
GitHub Projects are _useless_ as a _personal_ **Todo List** because they are limited to an Org or Repo.
What we _want_ is the ability to create `items` that span orgs/personal/private and other tasks IRL. 

This is the [**`App`**](https://github.com/dwyl/app) we are building and you are uniquely positioned to _help_ us test it! 💭 
It's _outlined_ in the [**`product roadmap`**](https://github.com/dwyl/product-roadmap) (please ask questions if unclear! 🙏)
This is an ["MVP"](https://github.com/dwyl/mvp#mvp-) it doesn't have anywhere _near_ all the features we would _like_ to have. ⌛ 
For example, I want to paste a link to a GitHub Issue and it load all the data: https://github.com/dwyl/app/issues/281 🔗 

## Todo

You can help us _immensely_:

+ [ ] ***Read*** through the [**`README.md`**](https://github.com/dwyl/mvp) 👀 
+ [ ] ***Use*** the MVP: [**`mvp.fly.dev`**](https://mvp.fly.dev/) on your Phone & Laptop (_login with your GitHub Account_) 📱 
+ [ ] ***Feedback*** what you think about the MVP and 💬 
  + [ ] ***Describe*** any features you need to make the App more _useful_ in the immediate term as separate issues. 📝

**Comment by Stephanymtr** [comment]
Hi @nelsonic, I read through all your notes and just finished setting up the MVP app. 🎉

![Screenshot_20220826-202034_Chrome.jpg](https://user-images.githubusercontent.com/91985721/186976759-a65ac42c-119c-40c4-90f1-3b400a32e8b3.jpg)

**Comment by iteles** [comment]
@Stephanymtr Can I suggest that each of these tasks should also include a link to an issue?

For now, issues are still the best way to share what you're working on and keep us up to date so we definitely still need issues and issue labels to be updated as you're working on them.
Having the link to the issue in your to-do list item means you have a direct and quick link to these (both for your reference of the complete detailed task that needs to be done and so you don't forget to update it!).

@nelsonic Given that we're still the ones helping Stephany determine the _priority_ of the issues, I wonder whether we should still either use projects or be clearer somehow about priorities in a way that both of us can see the issues being worked on and help determine priority?

**Comment by nelsonic** [comment]
@iteles totaloy agree that a way to prioritise tasks is critical to the usefulness/success of our App, please share your thoughts on: https://github.com/dwyl/app/issues/283 🙏

**Comment by LuchoTurtle** [comment]
unable to authenticate: 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/17494745/195299065-5dc6a5ba-f393-4606-af5c-510d220a5eb3.png">

going to keep trying but just wanted to log this ...

**Comment by nelsonic** [comment]
@LuchoTurtle thank you for alerting us to this. (as discussed verbally) 🔥 
We need to address this as **`P1`**. Please open a **`new`** issue and we can look at it now. 🆕

**Comment by LuchoTurtle** [comment]
Just got myself started with logging in and using the app for a wee and I have some small feedback from my short experience with using it. I tried to not repeat myself and I found myself agreeing with much of what @Stephanymtr had to say on [prioritization and organizing](https://github.com/dwyl/app/issues/283#issuecomment-1242325466). But I have a few suggestions/questions myself:

- What is the purpose of archiving? Personally, it appears a way of saying you are "done **done**" with the task at hand and you want to "delete it". As of now, the only difference between "Done" and "Archive" is purely semantical, because I can resume an archived task.

- Related to the previous, shouldn't I have a chance to permanently delete a task? Some tasks will be mundane/rudimentary and others will be week-long projects. I _understand_ if there are people interested in seeing the history of what they have done. But this history of archived tasks can easily get cluttered without any sort of organization (even if we have tag filtering per _state_ and _tag_) by everyday tasks such as "Taking the trash out". I think having a chance to **delete** would be a good option but perhaps I'm going about this the wrong way 😛 .

- Should pagination be implemented or are we going for an infinite scrolling experience with different filters and sorts?

- Reports. I know this is super not-MVP but the tracking time feature alone is a **goldmine** of data. We know _how much_ and _when_ (during the day, and week) users are working on a subject. Having insights about how the user is behaving when tackling tasks would be an amazing add-on.

Other than this, alongside the feedback on other issues, there's nothing really I can add more. So far, it's a super simple and minimalist experience, which I wholeheartedly like!

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for your great feedback. ❤️ 
Glad you've been able login and start using the MVP. 🎉 
1. **Archiving**: 100% agree that archiving is not clear. Thanks for confirming. ✅ 
For historical reasons (people reading this in the future), the MVP UI currently has the following filters:

![image](https://user-images.githubusercontent.com/194400/197038856-1b1099bf-a3e1-40b3-89d4-61b8bdd0a318.png)

Had already opened an issue to discuss the meaning of "**Active**" `items`: https://github.com/dwyl/mvp/issues/175
We can probably _remove_ the concept of `Archive` when we have `lists`. 💭 

2. **Permanently delete** an `item` ... 💥 worth opening a [separate issue](https://github.com/dwyl/app/issues) to capture the discussion on this. 

3. **Pagination** - at present nobody using the `MVP` has "too many" `items` so pagination hasn't been a priority I have **`324`** `items` and the interface + scrolling is still fast for me. `document.querySelectorAll('label').length -> 324`
But as soon as someone using the app notices a slow-down in the query response time we can prioritise this. 👌 

4. **Timers** - this is one of our USPs timers must _always_ work on all devices. 👍 

5. ***Reports*** - totally agree! Right now we are exposing _zero_ insights to the person/people using the App. 
  That will change as soon as we have **`groups`** and **`lists`**. 

Which report would you want to see _first_? Again, please open a [**`new issue`**](https://github.com/dwyl/app/issues) to discuss. 🙏

**Comment by iteles** [comment]
@LuchoTurtle To answer your question on the correction of timers (4th bullet), yes, absolutely: https://github.com/dwyl/app/issues/282#issuecomment-1281475762

**Comment by nelsonic** [comment]
@SimonLab, @iteles, @LuchoTurtle, @Stephanymtr & @seaneady 👋 
Please let me know your thoughts on the following Tags Progressive UI/UX:

<img width="2708" alt="image" src="https://user-images.githubusercontent.com/194400/214719780-a6594ba8-ec9b-48cc-a20c-664d855b2e1b.png">

Direct link to Figma page: https://www.figma.com/file/WrpkKGJNYZbeCzMRDVtvQLbC/dwyl-app?node-id=246%3A2

**Comment by panoramix360** [comment]
Hey!

I already contributed to the project with a [little PR](https://github.com/dwyl/mvp/pull/389) but I'd like to give some feedback :)

# Feedback/Suggestions
- **Small** When you type some description of a task and don't add it if you close the tab and open it again, the text is still there, I don't know if this was intended.
- I opened the `Done` tasks from the public website and there isn't any pagination, I believe it could be good to have some pagination to make it easier to see the tasks.
- A way of filtering/searching by tags or text.
- Show a small date from when the task was created. What do you think of grouping the tasks into sections? (Today, 2 days ago, etc)
- Add a way to remove a tag by clicking on it.
- **Small** When you click to resume the timer, it shows briefly `00:00:00` before continuing the count.
- Add a way to remove tasks after archiving. (this could be great to have an example of how to remove registers in the MVP since the purpose is to be educational as well)
- **Bug** Despite showing a disabled icon on the checkbox in Archived tasks, it's possible to uncheck it anyway.
- Add an Emoji button to add emojis to the text
- Add visual feedback that the tasks are clickable (I noticed this much later during the tests)
- Show the Timers date formatted in a friendly way. It could have a date picker as well. Screenshot below:
<img width="1005" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/c6211bfe-e964-4839-9f0b-36162cc50c49">

- It was a little tricky at first to understand this timer section above, maybe we can think of ways in making it clearer?
- What is the purpose of having a list of timers? Will the timers add up someplace else?
- In the tags screen, when a user clicks on a tag, we can go to the tasks screen and filter by this tag for easy searching.
- In the delete message of a tag, it could be nice to write that it will not affect the tasks using the tag.

I believe that for now, this is my feedback, sorry to make an extensive list hehe but I believe if the project work on some items described it will be more user-friendly.

Sorry if any of these were already an issue or mentioned before, I didn't search thoughtfully for them.

Thank you for the opportunity to help on this, it's looking nice :) I'd love to contribute more!

**Comment by nelsonic** [comment]
@panoramix360 stoked you found the project and were proactive in giving us feedback! 🎉 

# Quick answers:

+ Storing text in the `item.text` is intentional. 
  See: https://github.com/dwyl/mvp/issues/247
+ `pagination` is relevant for `people` who have _many_ tasks. 
  https://github.com/dwyl/mvp/issues/392
    Does the page load _particularly_ slowly in `Brazil` 🇧🇷 ⏳ 💭 🤷‍♂️ 
+ Filtering by tags is currently done by clicking/tapping on the tag. 
e.g: https://mvp.fly.dev/?filter_by=active&filter_by_tag=technical
  <img width="958" alt="image" src="https://github.com/dwyl/mvp/assets/194400/c584e7e8-86af-4ecd-9c58-eab66bfaa247">
  This is not immediately clear to new `people` using the `MVP` thanks for your feedback. 🙏 

+ Showing the `date` when an `item` was created, `last_updated` and `last_worked_on` is _very_ useful/insightful. 📅 
  The _reason_ we haven't added more detail to the interface - _yet_ - is to avoid cluttering. 
  See: https://github.com/dwyl/mvp/issues/393

+ **Removing `tags`** by clicking/tapping on the `x` in the `tag` is captured in the UX above: https://github.com/dwyl/mvp/issues/140#issuecomment-1404371243 ⬆️ and in https://github.com/dwyl/mvp/issues/221#issuecomment-1404384279 
<img width="604" alt="dwyl-mvp-x-to-remove-tag" src="https://github.com/dwyl/mvp/assets/194400/9bf6eea2-f8f7-4c07-902d-1bfe626a6c25">

   But ... it _appears_ that this is not described in an _issue_ with acceptance criteria.
   Let's _fix_ that! 

+ The timer showing `00:00:00` is, as you may have guessed, a `JS` timing issue which we can easily solve with a fade-in. Feel free to create an issue. 👌 
+ The "bug" on archived `items` being able to be unchecked is more of an "undocumented feature". 🙊 
  The checkbox shouldn't be disabled it, nobody _requested_ that  ... 💭 
  we can easily just remove the "disabled" state. ✅ 
+ `Emoji` support is 100% on the roadmap. 💯 Ref: https://github.com/dwyl/app/issues/275 
+ Visual feedback ... what do you have in mind? 🤔 
+ `Timers` in a more friendly format. Again, agreed. See: https://github.com/dwyl/app/issues/336
+ Making `timers` clearer. 100% agree. Have you read https://github.com/dwyl/product-roadmap/issues/43 ?
  Our plan is to have a _much_ more systematic onboarding experience. 🤞 
+ Having multiple `timers` will allow the `person` to keep better track of how they are spending their day. Good question. we don't have any interface for exposing this insight yet. ⏳ 
+ The `tags` screen is a stop-gap for managing `tags` and `colors`. There are several things we can do to improve this page including a summary of the number of `items` associated with the given `tag` and the `timers` (elapsed time) for the `tags`. Clicking through to `filter` by that `tag` is a relatively "low-hanging fruit": https://github.com/dwyl/mvp/issues/396
+ Inform people that deleting the `tag` will not affect the `item`. Agreed. This can be clarified. I've never deleted a `tag` so I've just not _seen_ this dialog ...
<img width="879" alt="image" src="https://github.com/dwyl/mvp/assets/194400/4df242a1-1ee2-4a84-a8c8-2a4cf233236e">

Thanks again for your feedback; it's immensely insightful/helpful/appreciated. 🙏 
Hope the answers are useful. 🤞 
Your contribution - and the fact that you were _able_ to navigate the codebase - is very encouraging. 🚀 
Thanks. 😊

**Comment by panoramix360** [comment]
hey! thank you @nelsonic, I'm glad to contribute to this project :)

Your descriptions/issues/posts are always very informative, thank you for taking the time to write this!

- `pagination`: it doesn't seem to take long here in Brazil hehe, requests data from the browser below:
<img width="336" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/6b8efe31-4c77-4f2f-934a-d9ebd720f96a">
- We could add a hover-darkening color to the tags to make them more clear to be clickable.
- I'll create the issue for the timer!
- Is there an issue with removing the disabled state of archived checkboxes?
- Regarding the visual effects on tasks, it could be a hover highlighting the task and a `cursor: pointer;` on the rows.
- In regards to the multiple timers, we could add a numeric reference like #1, #2, etc, but I believe there are better ideas than mine haha 

And yes, the answers are super useful!

Regarding the other subjects that I didn't point out above, I'll look into the issues that you referenced, thank you for pasting the link.

No worries!

I hope to contribute more to this project and others in the dwyl organization!

**Comment by panoramix360** [comment]
PS: @nelsonic notice that my last message was referring issues because I used `#1` without the code interpreter haha, edited now

**Comment by nelsonic** [comment]
@panoramix360 yeah, there's no way to "unfilter", 🤷‍♂️ 
at present we just click/tap on the logo in the header to reset.  🏠

**Comment by panoramix360** [comment]
Created an issue for us to discuss #398 :)
