### ISSUE TITLE
Chore: update badges 🙄 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#142]
I changed the repo name from **`app-mvp`** to just **`mvp`** but failed to update the badges 
so now we have:

[![Build Status](https://img.shields.io/travis/com/dwyl/app-mvp/master?color=bright-green&style=flat-square)](https://travis-ci.org/dwyl/app-mvp)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/app-mvp/master.svg?style=flat-square)](https://codecov.io/github/dwyl/app-mvp?branch=master)

https://github.com/dwyl/mvp/blame/aab29157f4f68a5f3bda5e9be8b0cf28e060b3c5/README.md#L17-L18
![image](https://user-images.githubusercontent.com/194400/187607887-ed03ea9d-7879-46c0-9f71-7dd29d3cfe72.png)

# Todo

+ [ ] Fix the badges in 
  + [ ] `REAMDE.md`
  + [ ] `BUILDIT.md`: https://github.com/dwyl/mvp/blame/aab29157f4f68a5f3bda5e9be8b0cf28e060b3c5/BUILDIT.md#L4
+ [ ] Create PR + Assign

**Comment by nelsonic** [comment]
This is a quick one. It's bugging me so I'm just going to get it done. 🐛

**Comment by nelsonic** [comment]
Borrowing from: https://github.com/dwyl/envar/blame/0f0fd7eed6aa6d3f0193fa246063f411604046a1/README.md#L10-L11
```md
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/dwyl/envar/Elixir%20CI?label=build&style=flat-square)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/envar/main.svg?style=flat-square)](http://codecov.io/github/dwyl/envar?branch=main)
```
Find-and-replace `envar` with `mvp`:

```md
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/dwyl/mvp/Elixir%20CI?label=build&style=flat-square)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/mvp/main.svg?style=flat-square)](http://codecov.io/github/dwyl/mvp?branch=main)
```

![GitHub Workflow Status](https://img.shields.io/github/workflow/status/dwyl/mvp/Elixir%20CI?label=build&style=flat-square)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/mvp/main.svg?style=flat-square)](http://codecov.io/github/dwyl/mvp?branch=main)

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/mvp/pull/143

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/187609557-f3b53fac-f25e-4ebd-9949-69aa5d95334b.png)
