### ISSUE TITLE
Feat: Edit Timer! [MVP] 📝 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#195]
Following on from #190 where you were able to **run the `MVP` on `localhost`** 🎉 (and update the docs! 🙌)
You should feel _confident_ enough in you knowledge of the project and `Phoenix/LiveView` skills
to create a **`new`** feature that has been _sorely_ lacking from the MVP. ⏳ 

This feature is described in more detail in the issue: https://github.com/dwyl/app/issues/282
But the gist from the MVP's perspective is the following:

# Todo

+ [x] When a `person` enters the `edit` mode for an `item`: 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/194400/198259019-db139085-74bb-4ee9-bbdd-d0122ba64283.png">

Should:

+ [x] display a list of the _past_ `timers` for that `item`:

![mvp-edit-timers](https://user-images.githubusercontent.com/194400/198269635-da3c0cea-2904-4c2e-bc08-615404c5af7f.png)

+ [x] Editing the `timer.start` or `timer.stop` in the **`UI`** and clicking/tapping the **`Update`** button will:
  + [x] Validate that both the `timer.start` and `timer.stop` are valid Date + Time 
    i.e: **`sanitise`** and attempt to ***`parse`*** the data
  + [x] Confirm that the `timer.stop` is not ***`before`*** the `timer.start` i.e. _invalid!_
  + [x] Save the data
    > **Note**: this is where having a complete history of changes is important to avoid too much "Time Travelling" ... 
    > Hence: https://github.com/dwyl/technology-stack/issues/106
    > But for MVP we don't care what happens we just want to test the simplest implementation of the feature.
+ [ ] Timers should not be allowed to overlap. 
i.e: the second timer cannot have `timer.start` set to a date+time earlier than the `timer.stop` of the first timer. 

We can add fancy UI/UX for timer input _later_ for now, just text is fine for MVP/Alpha!

> **Note**: @SimonLab was looking at editing/improving the Timer Functions in https://github.com/dwyl/mvp/issues/136
We should not _need_ to update those _yet_ (though we very much want to refactor them soon cause _my_ `code` is 🤮 ...)

# @LuchoTurtle 

+ [x] **Please _confirm_** you understand the requirement. 💬  (comment on this issue!)
+ [x] Create a **`new` branch** on your `localhost` with the tests, update to `BUILDIT.md` and code 🆕 
+ [x] Once you have _anything_ worth `commit`ting , `git push` and 💻 
+ [x] Create a **`PR`** e.g: "PR: Edit Timers #195` 🆕 
+ [x] Keep it assigned to yourself and `in-progress` until you feel it's in a reviewable state. 🧑‍💻

**Comment by nelsonic** [comment]
@LuchoTurtle busy reviewing your PR #196 
I'm unable to edit the `timer.start` on my `localhost` in the UI. 😕  (it's probably me ...)
I've recorded a video but it's too big to upload to GitHub ... 
Currently downloading [DaVinci Resolve](https://github.com/dwyl/video/issues/53#issuecomment-1309522383) to my MBP to trim and speed up the video. ⏳ 
But if you have time to sit with me this evening or tomorrow morning, LMK. 👌

**Comment by LuchoTurtle** [comment]
@nelsonic show me tomorrow morning. It should be fixeable. I've been so into Flutter and 99% close to finishing it. It was super worth it though, the other two issues you've assigned to me for the examples should be much easier after I'm done with `learn-flutter`.

Sorry for taking this long but I had to do a complete overhaul and added much more info and retained as much as possible.. 

I digress. No need to send a video. Demo me tomorrow on standup or before and I'll take a look at it 👉😎👉

**Comment by nelsonic** [comment]
As discussed on standup this morning ... 💬 
Editing the _current_ (active) timer was not one of the original requirements. ⬆️ 
So 100% agree that you couldn't _guess_ that it was a desirable feature. 👌 
But I'm fairly certain that our BDFL @iteles will want that functionality 💭 
and other people will too. [hypothesis...] 🧑‍🤝‍🧑 

So we shouldn't require a `timer.end` to be defined in order to update the **running** timer:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/194400/201063076-7ff063fd-0c4c-4596-9f5b-225ff133bbd6.png">

LMK if this is clear. 🙏

**Comment by LuchoTurtle** [comment]
@nelsonic didn't get to have the timer editing with stop at `nil` working because I noticed that I should be harsher on the verifications. I added a validation that checks if the timer that the user is verifying _overlaps_ with any of the others. It errors out if it does. 
I personally think this is important for calculating the **accumulating seconds**, which could be thrown off if the editing was free-for-allish.

**Comment by nelsonic** [comment]
Great spot! That should absolutely have been a requirement/acceptance criteria in the OP above! 💭  (adding it now!)

**Comment by nelsonic** [comment]
Concerned that we're including quite a few hundred lines of Library/Utility Code for Date/Time Parsing in the **`MVP`**:
+ https://github.com/dwyl/mvp/blame/356d69a2cf5a9e5459aef10089af6876628851fe/BUILDIT.md#L2774-L3080
+ https://github.com/dwyl/mvp/blob/356d69a2cf5a9e5459aef10089af6876628851fe/lib/app/datetime_parser.ex#L1-L196
+ https://github.com/dwyl/mvp/blob/356d69a2cf5a9e5459aef10089af6876628851fe/test/app/datetime_parser_test.exs#L1-L81

If we _need_ to write our own date/time parsing library this should be captured somewhere as a comment in this issue. 
Not _against_ writing our own parser, just need to know which requirements we had/have that aren't met by an _existing_ library. Because all code has to be _maintained_ which means we pay "rent" for each line we write. 💭

**Comment by LuchoTurtle** [comment]
[The reason I decided to not use Timex is that I didn't think it was worth it to import a whole library just for the sole purpose of parsing a date on a specified format. I tried to keep things lightweight on this one.](https://github.com/dwyl/mvp/pull/196#discussion_r1020817097)

However, you raise a good point about having to "pay rent" for each line we write. I thought it'd be a good idea to have a small parser util instead of importing a fully-fledged library just to parse strings into `DateTime`s. But since this is a point of concern, I'll switch to Timex 👍 (shame those tests will go to waste though haha 😂 )

**Comment by nelsonic** [comment]
@LuchoTurtle to be clear, I'm not at all against writing Library Code. We do it all the time, e.g: https://github.com/dwyl/useful
In fact we have a Date function on our backlog: https://github.com/dwyl/useful/issues/13

The only reason I'm flagging the addition of `DateTimeParser` in the **`MVP`** is that this kind of date-parsing code is **_not_ [business logic](https://en.wikipedia.org/wiki/Business_logic)**. If we _need_ to write a custom date parser then we should 100% **capture _all_ the requirements** and write our own Library, e.g: https://hex.pm/packages/dateutils

![image](https://user-images.githubusercontent.com/194400/201532980-21347a82-fce9-4777-b86e-e14d6dec7238.png)

But if we writing a parser just because we didn't do enough research into the available packages then ["That's a Nicht Nicht"](https://youtu.be/LazrAzBP_0I?t=219) 😜 

Again, perfectly happy for us to have our own `DateUtils` if we genuinely need it.
Even if it only has **_one_ function** to start with, that's fine.

**Comment by nelsonic** [comment]
Importing a library for a single function in the MVP is fine provided it meets our _exact_ needs. ✅ 
The `Elixir/Erlang` compiler will tree-shake the rest so it's efficient. 👌
