### ISSUE TITLE
Chore: DRY `socket` assigns code using `AuthPlug.assign_jwt_to_socket/3`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#215]
In light of https://github.com/dwyl/auth_plug/issues/86 we can now call:

```sh
socket = socket
  |> AuthPlug.assign_jwt_to_socket(&Phoenix.Component.assign_new/3, jwt)
```

# Todo

+ [x] Create a new `branch` for updating the code.

+ [x] Replace _both_ the instructions in the `BUILDIT.md` 

https://github.com/dwyl/mvp/blob/main/BUILDIT.md#62-create-auth-controller

+ [x] and the code in:

https://github.com/dwyl/mvp/blob/4d430b3459645ef52703b6342eca3e199ca3f75d/lib/app_web/controllers/auth_controller.ex#L5-L18

Can just be: 

```elixir
def on_mount(:default, _params, %{"jwt" => jwt} = _session, socket) do
  {:cont, AuthPlug.assign_jwt_to_socket(socket, &Phoenix.Component.assign_new/3, jwt)}
end
```

Which DRYs up this code very nicely. 

+ [x] Create a Pull Request, e.g: `"PR: DRY Assign JWT to Socket Code issue #215"`
+ [x] Assign the PR for review.

**Comment by nelsonic** [comment]
Anyone in the community of contributors is welcome to pick this up as a **`good first issue`**. 👌

**Comment by DuldR** [comment]
@nelsonic Hello! I'd love to take a wack at it if this is still available.

**Comment by nelsonic** [comment]
Hey @DuldR 👋 
This 100% still an issue. 💯 
You have **`write`** access to the repo, see: https://github.com/dwyl/mvp/invitations 🦄 
Please create a **`branch`** in the repo and Go for it! 🙌  
(_hopefully the above instructions are clear ... but if not, ask!_ 🙏)

> P.S: visit https://github.com/dwyl to accept Org Membership invitation 📥

**Comment by DuldR** [comment]
Added some questions over at the PR - https://github.com/dwyl/mvp/pull/225

**Comment by nelsonic** [comment]
@DuldR replied to your questions in the PR: https://github.com/dwyl/mvp/pull/225#issuecomment-1335058743 Thanks again! 👌

**Comment by DuldR** [comment]
Thank you for the feedback! Marked ready for review.

**Comment by nelsonic** [comment]
Merged. Thanks again! 🎉

**Comment by nelsonic** [comment]
Follow-up quest: #226 / #227 (sadly this one has to be done by me cause I have to publish a new version ... 🙄)
