### ISSUE TITLE
Feat: Metrics!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#245]
At present I don't have _any_ metrics/stats for my usage of the `MVP`. 😞 

# Story

## `People` _Using_ the `MVP`

As a **`person`** _using_ the @dwyl `MVP` to test the features and give feedback https://github.com/dwyl/mvp/issues/140
I **`want`** a **quick way** of viewing basic aggregate stats on how many `items` and `timers` I have created
**`So` that** I know how much I'm using the `MVP` to improve my personal effectiveness.

## `People` _Building_ the `MVP`

As a **`person`** _building_ the @dwyl `MVP` to solve a _personal_ problem faced with existing task trackers or ["personal productivity" tools...] 
I **`want`** to know if the `MVP` is being used by _anyone_ 
**`So` that** I know if the features are being used.

# Todo

+ [ ] Create a new endpoint `/stats` 
+ [ ] Create a `LiveView` page that renders the data and is updated in real-time
+ [ ] The `stats` channel should only be used for _aggregate_ data i.e. nothing personally identifiable.

Build a basic metrics dashboard that displays:

+ [ ] `person_id` 
+ [ ] Number of `items` 
+ [ ] Number of `timers` 

+ [ ] Display the data as a `<table`> (we can create pretty graphs later!)

> **Note**: this will be an _internal_ dashboard for now and will remain "anonymous".
But in the future it will be a **_personal_ dashboard** for the `person` _using_ the `App` to see how much and _when_ they are using it. 

So we will want a _visual_ representation of their usage similar to what `GitHub` has with their contribution graph:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/194400/210534246-aff13daa-c717-4e88-93bb-736a2a0464f7.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/194400/210534404-0beb72ed-b120-4971-952e-b704df7f7918.png">

We will encourage people to have "streaks" or at least to know they are making progress toward their goals.
This is "Step 1" on the Roadmap: [github.com/dwyl/product-roadmap#why-are-we-building-an-app](https://github.com/dwyl/product-roadmap/tree/02e07b0ab15cbe2337ccabb9de686496dba6a6fa#why-are-we-building-an-app)
Knowing that you are making **_daily_ progress** towards your goals is the **secret** to personal effectiveness and staying focussed long-term and not getting distracted ... See: [mattcutts.com/blog/seinfeld-calendar-trick](https://www.mattcutts.com/blog/seinfeld-calendar-trick/)

Longer term this will be a feature in itself. But for now we just need something basic. 🙏

**Comment by LuchoTurtle** [comment]
I can take this issue but I just have two questions:
- The dashboard is internal correct? It should show metrics for all users. How should I block access for 'regular users" so only `dwyl` members can access it? (implementation-wise)
- Would re-using the `live` channel that already exists be better? Or should I create a new channel dedicated to metrics? I feel like re-using would be easier/more readable but I can't figure out if it can be "too coupled" for long-term maintainability.

**Comment by nelsonic** [comment]
Hi @LuchoTurtle thanks for reading and replying. 🙏  
really hope you're feeling much better. 🤒 -> 😊 🤞 

To answer your two questions:

1. Yes, for now, the dashboard is "internal" but it won't be hidden or restricted by any `RBAC`, so ***anyone***/***everyone*** using the `MVP` can see the stats and consider it a "leaderboard" of sorts. 😜 
2. On a small `MVP` it doesn't really matter if you re-use the `live` channel cause the amount of data being sent will be _tiny_. But I'd say that the "best practice" would be to have a `stats` channel that is specific to the `/stats` page to reduce noise on the wire. 💭 

Thanks for looking into this. Will be _great_ to have some stats/metrics! 🎉 
And once the basics are done, we can do graphs too! 📈

**Comment by nelsonic** [comment]
This is what I had in mind:

```SQL
SELECT i.person_id,
COUNT(distinct i.id) AS "num_items", 
COUNT(distinct t.id) AS "num_timers"
FROM items i
LEFT JOIN timers t ON t.item_id = i.id
GROUP BY person_id
ORDER BY person_id
```

**Comment by nelsonic** [comment]
Basic AF: 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/194400/211565387-1c616fb6-5258-4583-939b-ed87831fb452.png">

But it's all we need to get started. 👌

**Comment by nelsonic** [comment]
Compact table:

![image](https://user-images.githubusercontent.com/194400/211566905-4ed581c4-c2e0-4676-889e-034677f388e4.png)

**Comment by nelsonic** [comment]
https://mvp.fly.dev/stats
<img width="815" alt="image" src="https://user-images.githubusercontent.com/194400/212057435-773d58fd-cebc-4c4c-8702-732797467702.png">

@LuchoTurtle please investigate why. 🔍 
If you get stuck ping me on Signal and we can remote-pair/debug via Zoom. 💭

**Comment by SimonLab** [comment]
It looks like the query is not correct:
![image](https://user-images.githubusercontent.com/6057298/212062092-a779b484-6c5f-44af-ae48-c841fc2da091.png)

(you can see the logs running flyctl logs inside the mvp app folder)

**Comment by LuchoTurtle** [comment]
Yeah @SimonLab , I'm working on a PR to fix this. 
The PR will also address a few bugs introduced which don't update the stats properly. 
I'll be opening an issue shortly.

**Comment by LuchoTurtle** [comment]
Created an issue https://github.com/dwyl/mvp/issues/261 and associated PR  https://github.com/dwyl/mvp/pull/262.

**Comment by nelsonic** [comment]
https://mvp.fly.dev/stats
![image](https://user-images.githubusercontent.com/194400/212190340-3362fbb8-0044-4597-b90c-eab22e4e224e.png)

Appears to be working. 👍 
Thanks again @LuchoTurtle
