### ISSUE TITLE
Feat: Add `PaperTrail` to MVP to enable `item.text` History!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#252]
The outcome of our `PaperTrail` learning [`SPIKE`] was successful: https://github.com/dwyl/phoenix-papertrail-demo
We need to outline how we are going to apply it to the `MVP` so that we can capture versions of `item.text`
so that there is a full history of the changes made to the `item`. 👍 

# Todo

@LuchoTurtle given that you have the most knowledge in the team of this, please:

+ [x] Outline how the DB Table Schema will change following the introduction of `PaperTrail` [please comment below!]
+ [x] Document all the steps to add `PaperTrail` in `buildit.md`, but link to the [dwyl/phoenix-papertrail-demo](https://github.com/dwyl/phoenix-papertrail-demo) for the "boilerplate" parts.
+ [x] Implement it with tests. 
+ [ ] Showcase it tomorrow at standup. 😉 

Don't worry, not asking you to implement the UI/UX for this, _yet_ ... just the backend! 👌

**Comment by LuchoTurtle** [comment]
With the introduction of Papertrail, the DB won't suffer many changes: only one table is going to be added to track item changes.
So the `items`, `items_tags`, `people`, `tags` and `timers` table won't suffer any changes. 

A *new table* will be introduced instead: `versions` (we perhaps could change it to `changes` or something you find more idiomatic). This table will be used to track changes to the `items` table (for now) but can be extended for other tables as well. It will reference the `people` table to track **who made the change**.

**Comment by nelsonic** [comment]
`versions` is fine as the table name. We can change it later if needed. 👍 (thanks!)
