### ISSUE TITLE
Proactively Save `item.text` on device to avoid losing data

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#253]
as noted in #247 I have lost data typed into the `item.text` `<textarea>` on several occasions. 🤦‍♂️ 
this is _hugely_ frustrating and as a `person` using this `MVP` I would quit the App immediately if it happened to me. 👎 

# Story

As a `person` using the @dwyl `App/MVP` 
I want to have the `item.text` I'm writing 
So that I don't lose any of it!

# Todo

+ [ ] Once the `PaperTrail` integration https://github.com/dwyl/mvp/issues/252 has been merged, we should be able to store the _versions_ of `item.text` so storing an _incomplete_ `item.text` e.g: `Buy mil" will become "Buy Milk from Waitrose" when fully captured. 
+ [ ] Implement a mechanism to save `item.text` on the Device 📱 
   so that if the page refreshes you check the device _first_ to see if there is some unfinished `text`. 
+  [ ] When the `item` is saved we can _clear_ the storage on the device. 

## Questions:

1. If the person has _multiple_ tabs open for the `MVP`, 
how do we allow them to have _multiple_ `item.text` in "draft" on the device? 💭 

2. Do we want to _sync_ draft text between connected clients so that I can start typing on one device and pick-up on another? 
or is this overcomplicating? Perhaps we can address this in the future. 💭

**Comment by nelsonic** [comment]
@SimonLab please LMK if you think this is satisfied by your recent PR #254 🙏

**Comment by SimonLab** [comment]
The PR https://github.com/dwyl/mvp/pull/254 fixed
> as noted in https://github.com/dwyl/mvp/issues/247 I have lost data typed into the item.text <textarea> on several occasions.

I think this issue can be closed
