### ISSUE TITLE
EPIC: Basic `REST API`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#256]
As discussed in: https://github.com/dwyl/app/issues/273 having a `REST` and `WebSocket` `API` is a **Top Priority** for us. 🔝 
We want _anyone_ to be able to securely query their data using the `API` and an `AUTH_API_KEY` or `JWT`; this is our **`API` Roadmap**. For now we just need something _super_ basic so that we can get moving on the `Flutter MVP`: https://github.com/dwyl/product-roadmap/issues/40

# Todo

We are breaking down this `EPIC` into 3 stages, an attempt chunk the work 
so that we can ship each stage as fast as possible. 
We expect there to be 3 separate Pull Requests; one for each stage.

Rather than extending the already _very_ long [**`BUILDIT.md`**](https://github.com/dwyl/mvp/blob/main/BUILDIT.md) file,
which is **`75 pages`** at the latest viewing:

![buildit-log-is-75-pages](https://user-images.githubusercontent.com/194400/211775823-2bae2de5-5fc7-4559-85c2-c18ca6e7ed42.png)

We will _instead_:

+ [ ] Create a **`new` file: `API.md`** in the root of the project where we write-up the details of the `API

## Stage 1: No Auth 📖 

+ [ ] Create an _unauthenticated_ API endpoint [`:authOptional`] in the `MVP` App 
       that enables the basic `CRUD` operations for `items` and `timers`:
+ [ ] `POST` to **`create`** an `item` anonymously, `/api/items/new`
  should only accept the `text` data and return an `item.id`, e.g: `200 '{"id":42}'` 
+ [ ] `PATCH` to `Edit/Update` an `item.text`: `/api/items/:id/update
+ [ ] `GET` to `READ` the contents of the `item`, e.g: `/api/items/:id`

You'll notice that we are _not_ doing `tags` in the _first_ stage; this is deliberate because there's quite a lot going on in the `tags` and we want to get the _first_ 

## Stage 2: `Tags` 🏷️ 

Creating `tags` and associating them to `items` is a bit more involved because it _can_ require _multiple_ API requests if we follow traditional `REST` conventions. We _should_ definitely do that for completeness. But for ***UX*** we should also allow people to create an `item` and specify the `tags` in a **_single_ `API` request**. 💭 

+ [ ] Create the `/api/tags` resource with:
+ [ ] `POST` for `/api/tags/new`
+ [ ] `GET` for `/api/tags/:id` and
+ [ ] `PATCH` for `/api/tags/:id/update`

Next:

+ [ ] Retrofit the `POST /api/items/new` and `PATCH /api/items/:id/update` endpoints to allow sending the tags on `item` creation and update.
e.g: `{"text": "my awesome update", "tags": "awesome, priority-1"}`  This will add some complexity so make sure you break it down into tiny + testable functions. 
+ [ ] Modify the `GET /api/items/:id` to return the `tags` with the `item` e.g: `{"text": "Learn elixir", "tags": "learn"}`

This is _definitely_ a denormalisation and potentially "frowned upon" by some `REST` purists. But we don't care. We only care about UX. If the person _using_ the `API` can make fewer requests and get their data faster, we are happy. 😊 

## Stage 3: With Authentication! 🔐 

Once the Basic `REST API` is working [deployed!] we will allow people to view a `JWT` within the `App` which they can use to make authenticated `API` Requests. There are a few extra steps to enable this so as soon as the previous 2 stages are complete (PRs merged & deployed) we will re-visit and expand on this stage. 👌 

> **Note**: What we will _eventually_ do is have an `api.dwyl.com` similar to how `GitHub` does it: https://docs.github.com/en/rest/overview/resources-in-the-rest-api so the `API` will run on a completely different server/service

@LuchoTurtle please take a look at this and LMK if it's clear enough for you to start work on it today. 🙏

**Comment by LuchoTurtle** [comment]
Just an update on this.
Since `:authOptional` has to be used (according to what is used in the issue), it's giving me lots of problems because of sessions (that don't exist when calling an API anonymously). 
Making a simple POST request is yielding me the following error:

`session not fetched, call fetch_session/2`

This error occurs in `auth_plug` and I've located where.  I'm just thinking of how I should change this code so it doesn't break the core functionality of the package and doesn't `fetch_session` two times needlessly. The error is in `get_jwt`, when calling [`get_session`.](https://github.com/dwyl/auth_plug/blob/1ac09260244d2c49263e347d460fd96353f300c6/lib/token.ex#L174).

It's weird, this error shouldn't be happening according to the [`Conn.Plug`'s](https://github.com/elixir-plug/plug/blob/15445099f5cdd9a196bd77c515e6fb82f1d4801d/lib/plug/conn.ex#L1699) source code, since the `:jwt` atom is being passed.

**Comment by nelsonic** [comment]
@LuchoTurtle in this instance a PR with tests is very welcome. 🙏

**Comment by nelsonic** [comment]
While testing the `API` using `cURL` on my localhost I noted that the `404` page for `/api` routes is `HTML` ...
Please see: https://github.com/dwyl/mvp/issues/269

**Comment by nelsonic** [comment]
At present the `API` route to `stop` a `timer` is: `/api/items/:item_id/timers/:id`
It should be `/api/timers/:id` I shouldn't need to specify the `:item_id`

**Comment by nelsonic** [comment]
Side Quest: #278

**Comment by LuchoTurtle** [comment]
Would it make sense to use it for our API docs? Or do you want to battle-test it first?

**Comment by nelsonic** [comment]
Fairly confident that doctave will work for our needs. 💭
The docs/tutorial seems pretty straightforward: https://cli.doctave.com/tutorial

question is: will we get API docs by using doctave or will we still need to use a tool like: https://github.com/open-api-spex/open_api_spex/blob/v3.16.1/README.md

**Comment by LuchoTurtle** [comment]
Should this issue be closed? A basic API Rest is already implemented (albeit without `auth`).

**Comment by nelsonic** [comment]
@LuchoTurtle as much as I would love to close this, `auth` is what makes this _useful_.
