### ISSUE TITLE
Chore: Use Timezone of Person using the `MVP`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#353]
At present the `timer.start` is the time on the `server` so when the clocks change due to daylight savings time 
the timers all start **`1 hour`** earlier than the clock of the `person` _using_ the `App`: 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/194400/231402960-f1b292b0-93e6-4d04-bbe3-ea92b67d6f84.png">

As you can see from this screenshot, the time on my Mac is `09:42`. 
The Timer has been running for `10 mins` since `08:32` ... 
it ***`should`*** have a `timer.start` of `09:32` ... 

We need to send the **timezone** from the `client` to the `server` and adjust the `timer.start` accordingly.
So someone using the `App` (currently `MVP`) has the correct `start` & `stop` time for their timers.
For web browser based `clients` we can get "offset" from using JS: https://stackoverflow.com/a/1809974/1148249

# Todo

+ [ ] get the `timer.start` and `timer.end` from the `client` 
+ [ ] the `timer.inserted_at` will still be defined by the `server` so we have some audit-ability...
+ [ ] figure out how to test this in `Elixir`-land ... 

@LuchoTurtle please confirm this is clear - or axsk a clarifying question - by commenting on this issue. 🙏

**Comment by LuchoTurtle** [comment]
It's clear. Though I feel like we shouldn't receive the `timer.start` and `timer.end` from the client. 
Instead, we should keep the way we are saving the dates as is and only *show the person* the datetime converted to the timezone they're located in. [`naive_datetime` already saves in UTC](https://elixirforum.com/t/why-use-utc-datetime-over-naive-datetime-for-ecto/32532) (although it would make sense to also use `utc_datetime` in the schema field definition to be more explicit).

The reason why I'm adamant about receiving the `timer.start` and `timer.end` from the client is because I think mixing up different timers in different timezones in the same workspace will not work in collaborative environments. Imagine if a user in one timezone starts a timer and another one in another zone ends it. I think this makes it much more difficult to manage.

By keeping the server within the same timezone and just *changing the representation* for each client is much simpler not only to implement but it also makes sense to keep the data consistent.

**Comment by nelsonic** [comment]
I think we _agree_ in principal. 💭 
We need a way of sending the timezone (offset from UTC) info from the `client` to the `server`
The server can still record the `timer.start`. 
But since we allow **_full_ control over `timer.start` and `timer.stop`** via the [`update_timer/2`](https://github.com/dwyl/mvp/blob/02869e8904dad19b4a71a2c6d306ce4376a67d1c/lib/app/timer.ex#L133) 
we are _already_ "_receiving the `timer.start` and `timer.end` from the client_" ... 🤔 

Storing the `timezone` or `offset_from_utc` in the `timer` record will allow the client-side conversion and will still allow people in various timezones to collaborate. It just means we need to perform additional calculations.

To your point on **_collaborative_ timers** for `people` in **_different_ timezones** ...
It implies that we need _two_ new columns/fields: `start_utc_offset` and `stop_utc_offset` 2️⃣ 
so that we can capture the timezone (offset) of the `client` that `start` & `stop` the `timer` ⏹️ 

We might need to think through this use case in a bit more detail and write some unit tests for scenarios. 
Because if someone in `London` _starts_ a `timer` at 09:00 (UTC+1) - this is 04:00 in `NYC` 🕓 
and then someone in `NYC` (EDT UTC-4) _stops_ that timer **1 hour _later_** at 05:00 (UTC-4) ...
The `timer` is being stopped `before` it started ... (obvs not really, but just in terms of timezones ...)
So we need to record all the `timer.start` & `timer.stop` in `UTC` (as we are currently doing) 
and then _display_ the correct time for each `client` according to their offset ...
The `timer` would still have `1 hour` elapsed but do we display the `timer.start` and `timer.stop`
as being _different_ for the two `people` in different timezones? 
Genuine implementation question ...

Ref: https://everytimezone.com/?t=64374600,1e0
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/194400/231701079-11a0a26d-2771-4e32-a828-3d72ac30e869.png">

I have an idea for how to resolve this in a simple way, but very keen to hear your thoughts. 🙏
