### ISSUE TITLE
Feat: Dark/Night Mode

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#362]
It's probably not good for my eyes, but I usually have my screens on max brightness. 😎 
Problem is: when we try and use the `MVP` in the evening the **`white` background** is **_insanely_ bright**! 

![image](https://user-images.githubusercontent.com/194400/234138898-c9254bce-c2b6-49c2-b6b0-32327f41f56f.png)

> **Note**: people are not very imaginative with capturing what is on their mind ... 🙃 
Maybe we need to change the placeholder / prompt text in the MVP ... 💭 

# How `GitHub` Handles "Light" / "Dark" Mode:

`GitHub` has "Theme preferences": https://github.com/settings/appearance which defaults to "**Light**" for historical reasons:
![image](https://user-images.githubusercontent.com/194400/234132208-32013a44-b29f-42d0-8be1-69a1adcf59ea.png)

You can manually select the "**Dark**" theme:

![image](https://user-images.githubusercontent.com/194400/234131799-8ef6d5e1-98b0-4cb1-8523-9d7d657410f5.png)

or set to "**Sync with _System_**":

![image](https://user-images.githubusercontent.com/194400/234132079-b1cf0456-8d5b-4abb-975d-3fd9f8d4ff4d.png)

# Tailwind "Dark" Mode:

https://tailwindcss.com/docs/dark-mode

![image](https://user-images.githubusercontent.com/194400/234133610-cbbb7c3c-f902-4c2f-8f1c-2ffd554b8e9b.png)

# Todo

+ [ ] Figure out how to get `Tailwind Dark Mode` working for our `MVP`
+ [ ] Save the `person's` preference to `settings.json` 
+ [ ] Document how we did it in https://github.com/dwyl/learn-tailwind including linking to the micro-PR in `MVP`

Quite like the theme switcher in: https://v1.daisyui.com/docs/add-themes
![daisyui-theme-switcher](https://user-images.githubusercontent.com/194400/234140608-f1738415-6489-47ca-a0f5-60242fa79328.png)
Uses https://github.com/saadeghi/theme-change made by the same chap as DaisyUI.
