### ISSUE TITLE
Chore/Feat: Use `Tailwind Ui Navbar` for `MVP` Top Nav

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#364]
At present the Main Nav for the `MVP` is rather inconsistent:

Anonymous:

![image](https://user-images.githubusercontent.com/194400/233988877-63b772c2-a5d2-4651-aec7-ac971cb6291f.png)

Logged in:

![image](https://user-images.githubusercontent.com/194400/233989214-ca8b2419-26b0-4ae9-a9bb-9d651b156028.png)

iOS Simulator (iPhone SE 2022): 

![image](https://user-images.githubusercontent.com/194400/233989501-a44b01fb-362d-489c-883e-1824cdc0da2c.png)

iOS _Real_ Device (Nelson's `iPhone 13`) on Mobile Safari:  (yes the timer is "on" but not updating ... 🙄)

![dwyl-mvp-top-nav-iphone-13-pro-mobile-safari](https://user-images.githubusercontent.com/194400/233990627-23fc7bc3-1d17-4ba0-8aee-b0f8f092d218.jpeg)

It doesn't look "bad" ... but it's definitely "Off":
+ The avatar image is much smaller than the @dwyl logo 
+ The logo is off-centre which looks weird ... 😕 
+ There's a random `tags` _white_ text in the Nav (which I can click to view my `tags`) ...
+ `Logout` `<button>` which feels like a Call to Action ... shouldn't be so prominent. 

We can do _much_ better. _Without_ much effort. 💭 

https://tailwindui.com/components/application-ui/navigation/navbars
![image](https://user-images.githubusercontent.com/194400/233988543-48349dc5-ad03-46c2-af91-14c7f911432a.png)

Adaptive (Mobile First):
![image](https://user-images.githubusercontent.com/194400/233988654-68b401c2-e6ba-4395-9561-f236df374ddb.png)

Menu expanded on "Mobile":

![image](https://user-images.githubusercontent.com/194400/233988742-0d61e2ba-b7fe-48fa-a7a8-00a3057581b3.png)

# Todo

+ [ ] Re-do the `MVP` Top Nav using the `Tailwind UI` > `Navbar` Component

Should:

+ [ ] Work effortlessly/flawlessly on both Mobile and Desktop 
+ [ ] Generate Menu from _static_ data for now i.e _not_ Dynamic.

> **Note**: Once we have `settings.json` working and `list.name="Main Menu"` https://github.com/dwyl/mvp/issues/363 we can update the Menu to be dynamic. But for now just updating the Interface to be more consistent would be a huge win. 🤞

**Comment by nelsonic** [comment]
@LuchoTurtle this should be doable. Please confirm you have access to TailwindUI. 🙏

**Comment by LuchoTurtle** [comment]
Confirmed access 🙏

Going to work on this now 👍
