### ISSUE TITLE
Feat: `item` pagination 1️⃣ 2️⃣ 3️⃣ ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#392]
As noted by @panoramix360 in https://github.com/dwyl/mvp/issues/140#issuecomment-1629885618 
when a `person` has _many_ `items` 
it can be useful to have `pagination`. 

# Context

 I currently have **2x** the number of `items` that the anonymous / guest `person` does in the `MVP` 
  and the interface is still perfectly manageable. see: https://mvp.fly.dev/stats 
<img width="938" alt="image" src="https://github.com/dwyl/mvp/assets/194400/ebaef07d-ef52-4f79-a53c-206b70c81ab8">
   Not saying pagination isn't important; it definitely is. 
But below `1k` `items` it's not _as_ important as some of the other features in the backlog; hence **`priority-3`**. 
    Yes, there are *many* items on the page (currently `281`) but it's not reached the point of being unresponsive. ⏳ 💔 
  The https://mvp.fly.dev/?filter_by=done in incognito (not authenticated) loads in _less_ than a `500ms` for me:
<img width="918" alt="image" src="https://github.com/dwyl/mvp/assets/194400/b6f2fec0-c267-422a-8efe-83b997c44ed7">

# Todo

+ [ ] @iteles to determine:
  + [ ] _What_ the pagination should _look_ like? ✨ 
  Can we just do the most basic thing like early `Google` did:
  ![image](https://github.com/dwyl/mvp/assets/194400/073f626c-8d2a-458c-a10e-484c57b7eeb4)
These days it's even simpler; just black and white with blue text links:
  <img width="351" alt="image" src="https://github.com/dwyl/mvp/assets/194400/e1e954da-5650-4871-8a87-cddb62a4754e">
  
  + [ ] How many `items` should the `person` or `list` have before it gets paginated? 💯 
 
Once the acceptance criteria are defined we can proceed with prioritisation and implementation. 👍

**Comment by nelsonic** [comment]
Tailwind UI - which we have unlimited access to - has a good-looking Pagination component: 
https://tailwindui.com/components/application-ui/navigation/pagination
<img width="1140" alt="tailwind-UI-pagination" src="https://github.com/dwyl/mvp/assets/194400/a61a2765-f57c-405c-8ffd-c390d75d3038">

Thinking we will just use this and skip "design". 🤔 
_Your_ Thoughts? 💭

**Comment by panoramix360** [comment]
It's nice that my feedback was used to add new issues 🎉🎉 

Since our design is simple and consistent, it should be enough to add the tailwind pagination.

**Comment by iteles** [comment]
I agree. For now, the tailwind implementation looks good and is in keeping with the rest of the design as @panoramix360 has noted 👏🏻

This can always be iterated on in the future. 

Right now, I think we need to have this at a higher number of items (such as 100) in order to ensure we're not missing important tasks until other features such as #145 are implemented.
