### ISSUE TITLE
Feat: `tags` page with tons more detail

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#396]
As noted by @panoramix360 in https://github.com/dwyl/mvp/issues/140#issuecomment-1629885618 💬 
At present the `/tags` page is quite basic:  https://mvp.fly.dev/tags this is _my_ tags page:
<img width="889" alt="mvp-nelson-tags" src="https://github.com/dwyl/mvp/assets/194400/098cfae2-aab8-4517-8c22-edae919847dd">
I have `118` `tags` at the time of writing: 

<img width="905" alt="dwyl-mvp-tags-nelson" src="https://github.com/dwyl/mvp/assets/194400/b99836f9-0188-45f6-8d3b-e3961d50512b">

Some of these are duplicates and there are a few typos. 🤦‍♂️ 
So in an ideal world, we'd also have a way of "merging" `tags`. 💭 
But I suspect I'm the _only_ `person` with `this` "problem" right now. 🙃 
So let's just focus on adding useful details to this page `before` doing anything "fancy" ... 👍 

# Todo

+ [x] Re-work/enhance the `/tags` page to include a _lot_ more info in a sortable table. 

Columns: 
+ `tag.text` - the "pill" of the `tag` with the `tag.color` applied (the current appearance, see above)
+ `tag.color` - the `hex` code for the `tag.color` - ideally clicking/tapping on this will open the color picker.  
+ `created_at` - when the `tag` was created
+ `latest` - the last time an `item` was tagged with this `tag`. 
+ `items` `count` - the of the number of `items` with this `tag` - clicking/tapping on the count will take you back to the `items` view with with the `filter=tag_name` so that you are seeing the `items` with that `tag` applied. 
+ `time` - the total time that has been logged on `items` with this `tag`
+ `edit` - the edit button for editing 
+ `delete` - delete the `tag` (though I'm not a fan of this permanent destruction ...)

This is a _perfect_ opportunity to make this a _look_ good by using `Tailwind UI -> With sortable headings`:
https://tailwindui.com/components/application-ui/lists/tables#component-7b5a46e74e475708d966ca31716f1771
<img width="1339" alt="image" src="https://github.com/dwyl/mvp/assets/194400/dfe2cfd9-d110-4e96-ac89-153d47b71b7d">

**Comment by panoramix360** [comment]
hey everyone!

Do you think this is ready to be developed?

I can take it :D

**Comment by nelsonic** [comment]
@panoramix360 go for it. 🙏

**Comment by panoramix360** [comment]
hey! I began the task :D

I was looking through the tags structure, and it seems it's not a LiveComponent, do you think we will need to transform it to a LiveComponent so we can make the sorting work?

I think we need to hehe, let me know what you guys think!

**Comment by nelsonic** [comment]
Please go ahead. Thanks. 🙏

**Comment by panoramix360** [comment]
hey! 'll give you guys an update.

I'm close to finishing this feature!

It's just missing:
- [ ] clicking/tapping on the count will take you back to the items view with the filter=tag_name so that you see the items with that tag applied.
- [ ] the total time that has been logged on items with this tag

<img width="957" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/1b343708-e246-4438-9c41-9ca4f0cb9a5e">

:D

**Comment by LuchoTurtle** [comment]
@panoramix360 looks amazing 😍 Thank you so much for your contributions, they're very much super appreciated!
Whenever you feel comfortable, you can open a PR so we can also help you out, if case need be :)

**Comment by panoramix360** [comment]
[Draft PR created](https://github.com/dwyl/mvp/pull/435) so you guys can begin the review 🕺 

I have to add the tests for the new screen 😅 

I have one problem that I want to ask for your help with so we can see how we can solve it.

I was able to build the sorting mechanism in the query, but it's not working with the virtual/calculated fields, I tried some stuff but only could make it work if I wrote hardcoded, but it does not work dynamically.

Do you have any idea what we could do? I'm thinking that maybe we will need to rewrite the query using Ecto Macros for it to work.

**Comment by nelsonic** [comment]
@panoramix360 if you can create a branch (and PR) we can help with anything you need. 👌

**Comment by nelsonic** [comment]
Hard-coded is already a good start.
I'd _much_ rather use a _client_-side package to sort data and just leave the `Ecto` query as simple as possible. 
e.g: [**`sortable`**](https://github.hubspot.com/sortable/docs/welcome)
![image](https://github.com/dwyl/mvp/assets/194400/df33c312-4692-46d7-8539-29f8ccc381b0)

> Note: there are _many_ libraries we can use ... we want something lightweight.
Feel free to research and suggest one that has ***filtering*** 
so `people` who have ***many*** tags can type a few characters and see the matching tags. 
e.g: https://www.bu.edu/tech/services/cccs/websites/www/wordpress/how-to/sortable-searchable-tables/

**Comment by panoramix360** [comment]
understood, but I think this probably should be an issue by itself, no?

Maybe just for now, I could sort using Elixir in the context of the LiveView (not using Ecto), what do you think?

I think that sorting by some library could be changed on a different PR.

**Comment by nelsonic** [comment]
Yeah, we can have a separate issue on sortable tables using a JS library. 👌
The progress you’ve already made on the /tags page is excellent. 🤩

**Comment by nelsonic** [comment]
Dedicated (separate) issue for the sorting/filtering: https://github.com/dwyl/mvp/issues/436

**Comment by panoramix360** [comment]
Probably this Issue could be solved after the PR merged :D

**Comment by LuchoTurtle** [comment]
Closing this off since #435 was merged :)
