### ISSUE TITLE
Feat: Improve Stats Page

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#397]
At present the `/stats` page is quite basic: https://mvp.fly.dev/stats
<img width="1201" alt="image" src="https://github.com/dwyl/mvp/assets/194400/c275c918-3172-4031-a6bb-95be2419522e">

We can add a _lot_ more info/insight to this page.

# Todo

+ [x] Make the table sortable. e.g. using: https://github.com/indgy/LittleBigTable - this makes sense with more interesting data.
+ [x] When the `person` _first_ joined (for authenticated `people`) 
+ [x] Total `timers` - the total _amount_ of elapsed time the person has logged using `timers` in the `MVP`.
+ [x] Latest `item` date (`item.created_at`) 
+ [x] "Me" - highlight the row for the `person` viewing the `/stats` page; make it _personal_ to them.

**Comment by panoramix360** [comment]
hey! :)

Can I take this one? Or it needs more refinement?

Please, point me to a `priority-1` that has already been defined if not :)

**Comment by LuchoTurtle** [comment]
Personally, I think you can get on with it. This issue and #396 seem to be plausible for @panoramix360 to develop. 
Do you agree @nelsonic ?

Since we are using Tailwind and have a license/access to https://tailwindui.com/, if you find any of their components suitable, you can comment on the PR and we'll drop the code in it on your request so you can work on it, if you want 😄

**Comment by nelsonic** [comment]
Indeed. I _opened_ several issue in _response_ to the superb feedback given by @panoramix360 on: https://github.com/dwyl/mvp/issues/140#issuecomment-1629885618 💬 
I'm _especially_ keen on enhancements that **_don't_ create `merge conflicts`** with https://github.com/dwyl/mvp/pull/345 ⏳ 
So yes, #397 (this issue) and #396 are _perfect_ for @panoramix360 (or anyone `else` in the community to work on). 🙏

**Comment by panoramix360** [comment]
I'll work on it then! Just assigned to me!

**Comment by nelsonic** [comment]
Awesome. Thanks. If you need access to [`Tailwind UI`](https://github.com/dwyl/learn-tailwind/issues/67) LMK (email me: `"#{firstname}@#{github_org_name}.com"`) 📧

**Comment by panoramix360** [comment]
I was looking through the components in Tailwind UI and it seems they already have the sortable headings:
https://tailwindui.com/components/application-ui/lists/tables#component-7b5a46e74e475708d966ca31716f1771
<img width="1343" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/55b81e65-44d1-4134-a4fe-9117071bc8ed">

Do we have access to it on the paid subscription?

I'll sent you an email to get access if possible.

**Comment by panoramix360** [comment]
About the task `when the person joined`, since we are using AuthPlug, it seems that it's using Phoenix Sessions to login.

This means that we are not storing the user in our database, right?

So to get this information I changed the query to bring the first date of the first item created by the user.

Can you tell me if this assumption is correct? Thanks! :D

<img width="580" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/7d288d2b-d4b6-486e-9ad9-eeec48982e7b">

**Comment by LuchoTurtle** [comment]
@panoramix360 
> Do we have access to it on the paid subscription?

Yes, we do :) You need a license to get the code of those components, which was what @nelsonic was trying to say in https://github.com/dwyl/mvp/issues/397#issuecomment-1642869336. If you give him an e-mail, he'll get you on with it.

> This means that we are not storing the user in our database, right?

In this `mvp`, we are not storing any information from the people that use it. Through[ `auth_plug` ](https://github.com/dwyl/auth_plug), we know which person is using the app by their `id`. For more context on how this `id` is created, you may check https://authdemo.fly.dev/people (and subsequently https://github.com/dwyl/auth). To make long story short, when you sign up through our auth service (either by Github, Google or Microsoft), our `auth` assigns you your ID from the info given by the provider you signed in from. 

So, our "first joined" assumption, although interesting, is not entirely accurate because they didn't necessarily join whenever they created the first item. However, because you don't really have access to this kind of information, I think it's a fair implementation (@nelsonic can correct me on this).

> Total timers - the total timers the person has.

Currently, the total timers (meaning the amount of `timer` objects a person has created) are already being shown on the page. Though I wager that summing all the timers and showcasing it in a different column would be an interesting insight to see how much time a person has spent on all the tasks they've created so far.

Again, thanks a lot for being proactive, it's wholeheartedly appreciated! If I'm wrong on anything that I've said here, @nelsonic will promptly correct me 👌

**Comment by panoramix360** [comment]
hey! thank you @LuchoTurtle 

My email is `lucasreis3000@gmail.com`

Regarding the `auth_plug`, I figured it was something like this, so since we don't have enough information on our database, I don't know how we can show this information reliably. I know that my solution is not entirely correct.

We can also create a `user` table and store this info there as soon as the `auth_plug` answer with an OK after the authentication. But I'd have to look through `auth_plug` docs if it's possible.

About the timers, I figure it would be something like this then:
<img width="573" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/b51f03e9-9a19-4292-9831-419e5385cc4e">

I'll format the time correctly, I'm showing in seconds, but we can show in minutes. But I wanted to show you the progress.

It's nice to contribute, I hope to contribute to other projects as well, especially the ones about learning. I was a professor at a University in the past (I teach Swift/iOS and React Native :D), so I really like this education focus that you guys are doing.

I'll wait for @nelsonic thoughts as well, but thank you for that :)

**Comment by nelsonic** [comment]
Hi @panoramix360, thanks for following up. All/always good questions. ❤️ 
You have an invite to join our `TailwindUI`; check your email. 📧 
Then remove your email from the previous comment to avoid `spam`. 🙅 

As @LuchoTurtle says, our goal is to store **_zero_ personally identifiable information** in the `MVP` (or `App`) and just store the bare minimum data required to interact with the `App` ... 
We consider the "first joined" date to be when they created their first `item`. 
Otherwise they only authenticated and didn't actually _interact_ with the `MVP/App`. 🥇 

As Lucho has said, the the "total timers" is the _amount_ of time as opposed to the `count` of timers. I have made it clearer in the OP. It's the **_elapsed_ time**.

All contributions are very welcome. If you create a `git branch` within the org instead of an `Fork` then your commits will run on the `GitHub Actions CI` each time you `git push`. :shipit: 

We are _huge_ fans of sharing _all_ of our learning so that _anyone_ can follow along regardless of where/who they are. Yes, even if that means we are "training" `ClosedAI` ... 🙄 If it means that `people` (assisted by LLMs) write better `code`, it's all good. 👌

**Comment by panoramix360** [comment]
hey! Thank you for the TailwindUI access, I'll begin the implementation of the sorted columns :)

Understood and agreed about storing zero info on the `MVP`. So I'll consider the first created item as the first joined, it's already implemented then!

Thank you for the clarification of the elapsed time! I implemented that already, I'll show it in the following format `00:00:00`.

Nice! I created a branch inside MVP for this current issue, I'll take a look at the other projects as well later :)

I'm seeing that you guys are creating some projects about Flutter, this interests me as well, I know a lot about the Mobile env like Android/iOS and even React Native, so it can be something that I can contribute.

Good know about sharing our learning, I really like that too!!!

**Comment by panoramix360** [comment]
@nelsonic and @LuchoTurtle 

Take a look at the elapsed time:
<img width="705" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/7bbc66a8-fed0-4bc5-8b49-981b955ed20c">
<img width="682" alt="image" src="https://github.com/dwyl/mvp/assets/2154092/812892db-1082-4ec5-b6f8-70719e160bbf">

I used the `:humanized` format on the Timex library.

I believe that's really nice :)

**Comment by nelsonic** [comment]
Good shout on using `Timex.Format.Duration.Formatters.Humanized`]()

**Comment by nelsonic** [comment]
Derp. didn't mean to close it. Some how clicked the wrong button. 🤦‍♂️ 
Thanks again for looking at this. 🙏

**Comment by panoramix360** [comment]
hey!

I'm finishing the sorting mechanism and it's looking great!

I decided to create a Table LiveComponent that can be used in other places on the application as well!

So I extracted the template and files to a separate place that can be reused.

And the sorting will be triggered when a column is clicked passing the sorting column as a LiveView event for the metrics to be sorted out.

I need more data to test this sorting on the database, but I can't log in locally, is there something that I need to do related to the AuthPlug to run this? Or is not possible to run locally?

**Comment by panoramix360** [comment]
Do you know if the `.env.sample` of the project is pointing to a real fly.dev application? I don't think so, right? hehe

**Comment by LuchoTurtle** [comment]
It's not :P 

In practicality, you'll probably only need to change the `AUTH_API_KEY` inside `env` and run `source .env` so the env variables are available.

To get your own `AUTH_API_KEY`, just follow the link I've sent https://github.com/dwyl/auth_plug#2-get-your-auth_api_key-. You basically just create a `New App` and use the `AUTH_API_KEY` given to you.

After these, if you run locally, you should have auth properly working on your local project :)

**Comment by panoramix360** [comment]
I managed to add items by hand to the database to make some tests.

I'll look into the auth later :)

The sorting is working :D I just need to create the Tailwind look now on the columns.

**Comment by nelsonic** [comment]
@panoramix360 if you push a branch and open a PR we can help with any parts you don't have time for. 👌

**Comment by panoramix360** [comment]
Done! I opened a PR so you guys can already review the work.

The only things missing are:
- Let the user click on the Column title and change the ordering by ASC or DESC.
- Add tests to the new code

**Comment by nelsonic** [comment]
https://mvp.fly.dev/stats
<img width="1220" alt="image" src="https://github.com/dwyl/mvp/assets/194400/5603272a-cbb4-463e-af6d-b496ac641244">

or incognito:
![image](https://github.com/dwyl/mvp/assets/194400/b9a45707-7db8-4d53-8dd1-8ccf812e3d99)

Thanks again @panoramix360 🎉

**Comment by LuchoTurtle** [comment]
Closing this since it's been completed 🥳
