### ISSUE TITLE
Chore: Update Node.js Version to `v20` used for API tests

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#404]
https://github.com/dwyl/mvp/actions/runs/5856288034?pr=345
![mvp-node-version-for-api-tests](https://github.com/dwyl/mvp/assets/194400/da746cf0-c693-4dba-8665-edd967987d25)

```sh
The following actions uses node12 which is deprecated 
and will be forced to run on node16: actions/checkout@v2. 
For more info: 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

# Todo

+ [ ] Red the changelog: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
+ [ ] Make any required updates
+ [ ] Create PR
+ [ ] Assign for review
+ [ ] Confirm working once merged.
