### ISSUE TITLE
Chore: `DRY` the `get_person_id/1` function duplicated in `app_live` and `stats`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#409]
As noted by @LuchoTurtle in https://github.com/dwyl/mvp/pull/399#discussion_r1299823896 the `get_person_id/1` function is duplicated in [`lib/app_web/live/stats_live.ex`](https://github.com/dwyl/mvp/pull/399/files/2a8c1042ab5e7ab1b460429e90b0984a9aa02653#diff-a95d4eaeafc8a6159649304ca27cf2aded518fe50396043356e8c6e51f8c863bR12)

# Todo

+ [x] create a new file for `person`-related functions e.g: `lib/app/person.ex`
+ [x] create the corresponding tests in `test/app/person_test.exs`
+ [x] lift & shift the function(s) that are reusable and place them, with docs in `lib/app/person.ex`
+ [x] Create a PR or include this as part of other work.

**Comment by LuchoTurtle** [comment]
Go for it :)

**Comment by nelsonic** [comment]
@panoramix360 yeah, as @LuchoTurtle says go for it and create a PR. If you get stuck ping us. Thanks! 🙏

**Comment by panoramix360** [comment]
Hey guys! sorry for the delay on this.

Here is the PR #415  :D

Let me know what you think!

**Comment by nelsonic** [comment]
@panoramix360 no need to apologise. 😉
Thanks for the PR. Merged. 👌
