### ISSUE TITLE
Chore: Tidy Drag & Drop Code for Consistency

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#416]
At present the code in `assets/js/app.js`, `lib/app_web/live/app_live.html.heex` and `lib/app_web/live/app_live.ex` has inconsistent naming of events and variables ... 🙃 

e.g: 

https://github.com/dwyl/mvp/blob/a7408a10e56ea651a5768c0650ebd373fed02daf/assets/js/app.js#L35-L58

`"remove-highlight"` should be `"remove_highlight"` and `"dragoverItem"` should be `"dragover_item"` for consistency.

# Todo

+ [x] Review all the code in these files and the corresponding tests `test/app_web/live/app_live_test.exs` and update for consistency. 👩‍💻 
+ [x] Ensure that all tests still pass and functionality still works. ✅ 
+ [x] Create PR and assign for review. :shipit:

**Comment by LuchoTurtle** [comment]
I can open a small PR over the weekend 👌

**Comment by nelsonic** [comment]
PR: #419 merged. ✅ 
Thanks @LuchoTurtle 👌
