### ISSUE TITLE
Feat: `items_with_timers/1` -> `items_with_timers/2` (`list_cid`)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#423]
At present the route for the `/lists` on the #165 PR is currently:
https://github.com/dwyl/mvp/blob/10a2a6aa9da79837b6eea229e213b937e913dcfe/lib/app_web/router.ex#L32

i.e: there is no "page" to `:show` the `list`.
There is no function in the `controller` for displaying the `list`.
_However_ we planned ahead for this when introducing `lists`...
The `items_with_timers/1` function currently 

```elixir
  def items_with_timers(person_id \\ 0) do
    all_list = App.List.get_all_list_for_person(person_id)
    seq = App.List.get_list_seq(all_list)

    ...
```
https://github.com/dwyl/mvp/blob/b8aee0e3c29d0cb45025595131248c08fbbf6a31/lib/app/item.ex#L216C7-L218

We need to update the function to accept a `list_cid` as the second parameter. 
and lookup the `list` using `get_list_by_cid!/1`
Then we can filter the `items` based on the `list.seq`.

# Todo

+ [x] Add `list_cid` argument to `items_with_timers/1` to make it `items_with_timers/2` 
  + [x] if `list_cid` is `nil` then default to the "all" `list`.
+ [x] Create `items_with_timers/2` test with a different `list_cid`.

**Comment by nelsonic** [comment]
Included in: https://github.com/dwyl/mvp/pull/165 :shipit:
