### ISSUE TITLE
Feat: Sort + Filter `Tags` Table Columns/Values using `JS` Lib

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#436]
As noted in: https://github.com/dwyl/mvp/issues/396#issuecomment-1776753503 the `/tags` page https://github.com/dwyl/mvp/pull/435 is looking great! 😍 
Rather than complicating the `Ecto` query by adding the sorting/filtering server-side,
we're going to select a `JS` library that can do it with the data already loaded in the browser. 

# Todo

+ [ ] Do a brief search of the available standalone libraries that do sorting & filtering of `HTML` Tables
> **Note**: it appears to be reasonably straightforward to do this with `Alpine.js`: https://codepen.io/ryangjchandler/pen/WNQQKeR
  + [ ] Share your findings for suggested libraries
+ [ ] Implement the sorting + filtering using the `JS` library
+ [ ] Create a Pull Request 
+ [ ] Request review.
